### YamlMime:ManagedReference
items:
- uid: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration
  commentId: T:Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration
  id: IEventLoopGroupFactoryConfiguration
  parent: Catalyst.Abstractions.IO.EventLoop
  children:
  - Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.TcpClientHandlerWorkerThreads
  - Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.TcpServerHandlerWorkerThreads
  - Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.UdpClientHandlerWorkerThreads
  - Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.UdpServerHandlerWorkerThreads
  langs:
  - csharp
  - vb
  name: IEventLoopGroupFactoryConfiguration
  nameWithType: IEventLoopGroupFactoryConfiguration
  fullName: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration
  type: Interface
  source:
    remote:
      path: src/Catalyst.Abstractions/IO/EventLoop/IEventLoopGroupFactoryConfiguration.cs
      branch: gh-pages
      repo: https://github.com/catalyst-network/Catalyst.Framework.git
    id: IEventLoopGroupFactoryConfiguration
    path: ../src/Catalyst.Abstractions/IO/EventLoop/IEventLoopGroupFactoryConfiguration.cs
    startLine: 25
  assemblies:
  - Catalyst.Abstractions
  namespace: Catalyst.Abstractions.IO.EventLoop
  syntax:
    content: public interface IEventLoopGroupFactoryConfiguration
    content.vb: Public Interface IEventLoopGroupFactoryConfiguration
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.TcpServerHandlerWorkerThreads
  commentId: P:Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.TcpServerHandlerWorkerThreads
  id: TcpServerHandlerWorkerThreads
  parent: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration
  langs:
  - csharp
  - vb
  name: TcpServerHandlerWorkerThreads
  nameWithType: IEventLoopGroupFactoryConfiguration.TcpServerHandlerWorkerThreads
  fullName: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.TcpServerHandlerWorkerThreads
  type: Property
  source:
    remote:
      path: src/Catalyst.Abstractions/IO/EventLoop/IEventLoopGroupFactoryConfiguration.cs
      branch: gh-pages
      repo: https://github.com/catalyst-network/Catalyst.Framework.git
    id: TcpServerHandlerWorkerThreads
    path: ../src/Catalyst.Abstractions/IO/EventLoop/IEventLoopGroupFactoryConfiguration.cs
    startLine: 29
  assemblies:
  - Catalyst.Abstractions
  namespace: Catalyst.Abstractions.IO.EventLoop
  summary: Gets or sets the TCP server threads.
  example: []
  syntax:
    content: int TcpServerHandlerWorkerThreads { get; set; }
    parameters: []
    return:
      type: System.Int32
      description: The TCP server threads.
    content.vb: Property TcpServerHandlerWorkerThreads As Integer
  overload: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.TcpServerHandlerWorkerThreads*
  modifiers.csharp:
  - get
  - set
- uid: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.TcpClientHandlerWorkerThreads
  commentId: P:Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.TcpClientHandlerWorkerThreads
  id: TcpClientHandlerWorkerThreads
  parent: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration
  langs:
  - csharp
  - vb
  name: TcpClientHandlerWorkerThreads
  nameWithType: IEventLoopGroupFactoryConfiguration.TcpClientHandlerWorkerThreads
  fullName: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.TcpClientHandlerWorkerThreads
  type: Property
  source:
    remote:
      path: src/Catalyst.Abstractions/IO/EventLoop/IEventLoopGroupFactoryConfiguration.cs
      branch: gh-pages
      repo: https://github.com/catalyst-network/Catalyst.Framework.git
    id: TcpClientHandlerWorkerThreads
    path: ../src/Catalyst.Abstractions/IO/EventLoop/IEventLoopGroupFactoryConfiguration.cs
    startLine: 33
  assemblies:
  - Catalyst.Abstractions
  namespace: Catalyst.Abstractions.IO.EventLoop
  summary: Gets or sets the TCP client threads.
  example: []
  syntax:
    content: int TcpClientHandlerWorkerThreads { get; set; }
    parameters: []
    return:
      type: System.Int32
      description: The TCP client threads.
    content.vb: Property TcpClientHandlerWorkerThreads As Integer
  overload: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.TcpClientHandlerWorkerThreads*
  modifiers.csharp:
  - get
  - set
- uid: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.UdpServerHandlerWorkerThreads
  commentId: P:Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.UdpServerHandlerWorkerThreads
  id: UdpServerHandlerWorkerThreads
  parent: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration
  langs:
  - csharp
  - vb
  name: UdpServerHandlerWorkerThreads
  nameWithType: IEventLoopGroupFactoryConfiguration.UdpServerHandlerWorkerThreads
  fullName: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.UdpServerHandlerWorkerThreads
  type: Property
  source:
    remote:
      path: src/Catalyst.Abstractions/IO/EventLoop/IEventLoopGroupFactoryConfiguration.cs
      branch: gh-pages
      repo: https://github.com/catalyst-network/Catalyst.Framework.git
    id: UdpServerHandlerWorkerThreads
    path: ../src/Catalyst.Abstractions/IO/EventLoop/IEventLoopGroupFactoryConfiguration.cs
    startLine: 37
  assemblies:
  - Catalyst.Abstractions
  namespace: Catalyst.Abstractions.IO.EventLoop
  summary: Gets or sets the UDP server threads.
  example: []
  syntax:
    content: int UdpServerHandlerWorkerThreads { get; set; }
    parameters: []
    return:
      type: System.Int32
      description: The UDP server threads.
    content.vb: Property UdpServerHandlerWorkerThreads As Integer
  overload: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.UdpServerHandlerWorkerThreads*
  modifiers.csharp:
  - get
  - set
- uid: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.UdpClientHandlerWorkerThreads
  commentId: P:Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.UdpClientHandlerWorkerThreads
  id: UdpClientHandlerWorkerThreads
  parent: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration
  langs:
  - csharp
  - vb
  name: UdpClientHandlerWorkerThreads
  nameWithType: IEventLoopGroupFactoryConfiguration.UdpClientHandlerWorkerThreads
  fullName: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.UdpClientHandlerWorkerThreads
  type: Property
  source:
    remote:
      path: src/Catalyst.Abstractions/IO/EventLoop/IEventLoopGroupFactoryConfiguration.cs
      branch: gh-pages
      repo: https://github.com/catalyst-network/Catalyst.Framework.git
    id: UdpClientHandlerWorkerThreads
    path: ../src/Catalyst.Abstractions/IO/EventLoop/IEventLoopGroupFactoryConfiguration.cs
    startLine: 41
  assemblies:
  - Catalyst.Abstractions
  namespace: Catalyst.Abstractions.IO.EventLoop
  summary: Gets or sets the UDP client threads.
  example: []
  syntax:
    content: int UdpClientHandlerWorkerThreads { get; set; }
    parameters: []
    return:
      type: System.Int32
      description: The UDP client threads.
    content.vb: Property UdpClientHandlerWorkerThreads As Integer
  overload: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.UdpClientHandlerWorkerThreads*
  modifiers.csharp:
  - get
  - set
references:
- uid: Catalyst.Abstractions.IO.EventLoop
  commentId: N:Catalyst.Abstractions.IO.EventLoop
  name: Catalyst.Abstractions.IO.EventLoop
  nameWithType: Catalyst.Abstractions.IO.EventLoop
  fullName: Catalyst.Abstractions.IO.EventLoop
- uid: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.TcpServerHandlerWorkerThreads*
  commentId: Overload:Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.TcpServerHandlerWorkerThreads
  name: TcpServerHandlerWorkerThreads
  nameWithType: IEventLoopGroupFactoryConfiguration.TcpServerHandlerWorkerThreads
  fullName: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.TcpServerHandlerWorkerThreads
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.TcpClientHandlerWorkerThreads*
  commentId: Overload:Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.TcpClientHandlerWorkerThreads
  name: TcpClientHandlerWorkerThreads
  nameWithType: IEventLoopGroupFactoryConfiguration.TcpClientHandlerWorkerThreads
  fullName: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.TcpClientHandlerWorkerThreads
- uid: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.UdpServerHandlerWorkerThreads*
  commentId: Overload:Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.UdpServerHandlerWorkerThreads
  name: UdpServerHandlerWorkerThreads
  nameWithType: IEventLoopGroupFactoryConfiguration.UdpServerHandlerWorkerThreads
  fullName: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.UdpServerHandlerWorkerThreads
- uid: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.UdpClientHandlerWorkerThreads*
  commentId: Overload:Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.UdpClientHandlerWorkerThreads
  name: UdpClientHandlerWorkerThreads
  nameWithType: IEventLoopGroupFactoryConfiguration.UdpClientHandlerWorkerThreads
  fullName: Catalyst.Abstractions.IO.EventLoop.IEventLoopGroupFactoryConfiguration.UdpClientHandlerWorkerThreads
